import { Obstacle } from "./lib/type"

// Map boundaries:
// X range → 5 (left) to 34 (right)
// Y range → 1 (top) to 24 (bottom)

export const MAP_LAYOUT = {
  layout1: [
    // cloud
    { name: "cloud", x: 3, y: 12 },
    { name: "cloud", x: 32, y: 18 },
    { name: "cloud", x: 16, y: 10 },
    { name: "cloud1", x: 24, y: 7 },
    { name: "cloud1", x: 32, y: 5 },
    { name: "cloud1", x: 15, y: 24 },
    // rock
    { name: "rock", x: 15, y: 12 },
    { name: "rock", x: 12, y: 12 },
    { name: "rock", x: 13, y: 12 },
    { name: "rock", x: 14, y: 12 },
    { name: "rock", x: 12, y: 5 },
    { name: "rock", x: 13, y: 5 },
    { name: "rock", x: 14, y: 5 },
    { name: "rock", x: 15, y: 5 },
    { name: "rock", x: 16, y: 5 },
    { name: "rock", x: 17, y: 5 },
    { name: "rock", x: 18, y: 5 },
    { name: "rock", x: 17, y: 15 },
    { name: "rock", x: 22, y: 15 },
    { name: "rock", x: 10, y: 22 },
    { name: "rock", x: 11, y: 22 },
    { name: "rock", x: 28, y: 22 },
    { name: "rock", x: 29, y: 22 },
    { name: "rock", x: 19, y: 15 },
    { name: "rock", x: 20, y: 15 },
    // bush
    { name: "bush", x: 8, y: 12 },
    { name: "bush", x: 9, y: 12 },
    { name: "bush", x: 10, y: 12 },
    { name: "bush", x: 11, y: 12 },
    { name: "bush", x: 16, y: 12 },
    { name: "bush", x: 17, y: 12 },
    { name: "bush", x: 18, y: 12 },
    { name: "bush", x: 19, y: 12 },
    { name: "bush", x: 20, y: 12 },
    { name: "bush", x: 21, y: 12 },
    { name: "bush", x: 22, y: 12 },
    { name: "bush", x: 23, y: 12 },
    { name: "bush", x: 28, y: 12 },
    { name: "bush", x: 29, y: 12 },
    { name: "bush", x: 30, y: 12 },
    { name: "bush", x: 31, y: 12 },
    { name: "bush", x: 34, y: 23 },
    { name: "bush", x: 33, y: 23 },
    { name: "bush", x: 32, y: 23 },
    { name: "bush", x: 31, y: 23 },
    { name: "bush", x: 30, y: 23 },
    { name: "bush", x: 29, y: 23 },
    { name: "bush", x: 5, y: 23 },
    { name: "bush", x: 7, y: 23 },
    { name: "bush", x: 6, y: 23 },
    { name: "bush", x: 8, y: 23 },
    { name: "bush", x: 9, y: 23 },
    { name: "bush", x: 10, y: 23 },
    // rock
    { name: "rock", x: 24, y: 12 },
    { name: "rock", x: 25, y: 12 },
    { name: "rock", x: 26, y: 12 },
    { name: "rock", x: 27, y: 12 },
    { name: "rock", x: 21, y: 5 },
    { name: "rock", x: 22, y: 5 },
    { name: "rock", x: 23, y: 5 },
    { name: "rock", x: 24, y: 5 },
    { name: "rock", x: 25, y: 5 },
    { name: "rock", x: 26, y: 5 },
    { name: "rock", x: 27, y: 5 },
    // up - right column
    { name: "rock", x: 28, y: 11 },
    { name: "rock", x: 28, y: 10 },
    { name: "rock", x: 28, y: 9 },
    { name: "rock", x: 28, y: 8 },
    { name: "rock", x: 28, y: 7 },
    { name: "rock", x: 28, y: 6 },
    { name: "rock", x: 28, y: 5 },
    // up - left column
    { name: "rock", x: 11, y: 11 },
    { name: "rock", x: 11, y: 10 },
    { name: "rock", x: 11, y: 9 },
    { name: "rock", x: 11, y: 8 },
    { name: "rock", x: 11, y: 7 },
    { name: "rock", x: 11, y: 6 },
    { name: "rock", x: 11, y: 5 },
    // chest
    { name: "chest", x: 15, y: 3 },
    { name: "chest", x: 30, y: 20 },
    // tree
    { name: "tree", x: 8, y: 4 },
    { name: "tree", x: 30, y: 4 },
    { name: "tree", x: 8, y: 16 },
    { name: "tree", x: 8, y: 18 },
    { name: "tree", x: 10, y: 16 },
    { name: "tree", x: 12, y: 16 },
    { name: "tree", x: 30, y: 16 },
    { name: "tree", x: 30, y: 18 },
    { name: "tree", x: 28, y: 16 },
    { name: "tree", x: 26, y: 16 },
    // wood base
    { name: "woodFenceNoEdge", x: 18, y: 24 },
    { name: "woodFenceNoEdge", x: 18, y: 23 },
    { name: "woodFenceNoEdge", x: 18, y: 22 },
    { name: "woodFenceNoEdge", x: 19, y: 22 },
    { name: "woodFenceNoEdge", x: 21, y: 24 },
    { name: "woodFenceNoEdge", x: 21, y: 23 },
    { name: "woodFenceNoEdge", x: 21, y: 22 },
    { name: "woodFenceNoEdge", x: 20, y: 22 },
    // plant
    { name: "pot_plant", x: 16, y: 18 },
    { name: "pot_plant", x: 12, y: 22 },
    { name: "pot_plant", x: 14, y: 20 },
    { name: "pot_plant", x: 22, y: 18 },
    { name: "pot_plant", x: 26, y: 22 },
    { name: "pot_plant", x: 24, y: 20 },
    { name: "pot_plant", x: 20, y: 9 },
    { name: "pot_plant", x: 18, y: 9 },
    { name: "pot_plant", x: 5, y: 10 },
    { name: "pot_plant", x: 33, y: 10 },
  ] as Obstacle[],
  layout2: [
    // clouds
    { name: "cloud", x: 12, y: 2 },
    { name: "cloud1", x: 26, y: 3 },
    { name: "cloud", x: 20, y: 4 },
    { name: "cloud1", x: 18, y: 3 },
    { name: "cloud", x: 22, y: 2 },
    // rock
    { name: "rock", x: 17, y: 11 },
    { name: "rock", x: 18, y: 11 },
    { name: "rock", x: 19, y: 11 },
    { name: "rock", x: 20, y: 11 },
    { name: "rock", x: 21, y: 11 },
    { name: "rock", x: 22, y: 11 },
    { name: "rock", x: 18, y: 13 },
    { name: "rock", x: 19, y: 13 },
    { name: "rock", x: 20, y: 13 },
    { name: "rock", x: 21, y: 13 },
    { name: "rock", x: 9, y: 6 },
    { name: "rock", x: 10, y: 6 },
    { name: "rock", x: 11, y: 6 },
    { name: "rock", x: 12, y: 6 },
    { name: "rock", x: 12, y: 7 },
    { name: "rock", x: 12, y: 8 },
    { name: "rock", x: 9, y: 9 },
    { name: "rock", x: 10, y: 9 },
    { name: "rock", x: 11, y: 9 },
    { name: "rock", x: 12, y: 9 },
    { name: "rock", x: 27, y: 6 },
    { name: "rock", x: 28, y: 6 },
    { name: "rock", x: 29, y: 6 },
    { name: "rock", x: 30, y: 6 },
    { name: "rock", x: 27, y: 7 },
    { name: "rock", x: 27, y: 8 },
    { name: "rock", x: 27, y: 9 },
    { name: "rock", x: 28, y: 9 },
    { name: "rock", x: 29, y: 9 },
    { name: "rock", x: 30, y: 9 },
    { name: "rock", x: 14, y: 10 },
    { name: "rock", x: 15, y: 10 },
    { name: "rock", x: 16, y: 10 },
    { name: "rock", x: 23, y: 10 },
    { name: "rock", x: 24, y: 10 },
    { name: "rock", x: 25, y: 10 },
    { name: "rock", x: 14, y: 15 },
    { name: "rock", x: 15, y: 15 },
    { name: "rock", x: 16, y: 15 },
    { name: "rock", x: 23, y: 15 },
    { name: "rock", x: 24, y: 15 },
    { name: "rock", x: 25, y: 15 },
    { name: "rock", x: 22, y: 22 },
    { name: "rock", x: 23, y: 22 },
    { name: "rock", x: 24, y: 22 },
    { name: "rock", x: 25, y: 22 },
    { name: "rock", x: 14, y: 22 },
    { name: "rock", x: 15, y: 22 },
    { name: "rock", x: 16, y: 22 },
    { name: "rock", x: 17, y: 22 },
    { name: "rock", x: 12, y: 21 },
    { name: "rock", x: 27, y: 21 },
    { name: "rock", x: 34, y: 22 },
    { name: "rock", x: 5, y: 22 },
    // bush
    { name: "bush", x: 13, y: 9 },
    { name: "bush", x: 14, y: 9 },
    { name: "bush", x: 15, y: 9 },
    { name: "bush", x: 24, y: 9 },
    { name: "bush", x: 25, y: 9 },
    { name: "bush", x: 26, y: 9 },
    { name: "bush", x: 13, y: 14 },
    { name: "bush", x: 14, y: 14 },
    { name: "bush", x: 15, y: 14 },
    { name: "bush", x: 24, y: 14 },
    { name: "bush", x: 25, y: 14 },
    { name: "bush", x: 26, y: 14 },
    { name: "bush", x: 5, y: 3 },
    { name: "bush", x: 6, y: 3 },
    { name: "bush", x: 9, y: 3 },
    { name: "bush", x: 10, y: 3 },
    { name: "bush", x: 11, y: 3 },
    { name: "bush", x: 28, y: 3 },
    { name: "bush", x: 29, y: 3 },
    { name: "bush", x: 30, y: 3 },
    { name: "bush", x: 33, y: 3 },
    { name: "bush", x: 34, y: 3 },
    { name: "bush", x: 17, y: 20 },
    { name: "bush", x: 18, y: 20 },
    { name: "bush", x: 21, y: 20 },
    { name: "bush", x: 22, y: 20 },
    { name: "bush", x: 17, y: 21 },
    { name: "bush", x: 18, y: 21 },
    { name: "bush", x: 21, y: 21 },
    { name: "bush", x: 22, y: 21 },
    // trees
    { name: "tree", x: 26, y: 18 },
    { name: "tree", x: 32, y: 11 },
    { name: "tree", x: 6, y: 11 },
    { name: "tree", x: 8, y: 11 },
    { name: "tree", x: 30, y: 11 },
    { name: "tree", x: 6, y: 18 },
    { name: "tree", x: 6, y: 14 },
    { name: "tree", x: 6, y: 20 },
    { name: "tree", x: 6, y: 16 },
    { name: "tree", x: 32, y: 18 },
    { name: "tree", x: 32, y: 14 },
    { name: "tree", x: 32, y: 20 },
    { name: "tree", x: 32, y: 16 },
    { name: "tree", x: 10, y: 12 },
    { name: "tree", x: 12, y: 18 },
    { name: "tree", x: 28, y: 12 },
    // pot plant
    { name: "pot_plant", x: 7, y: 3 },
    { name: "pot_plant", x: 18, y: 16 },
    { name: "pot_plant", x: 20, y: 16 },
    { name: "pot_plant", x: 31, y: 3 },
    { name: "pot_plant", x: 16, y: 18 },
    { name: "pot_plant", x: 22, y: 18 },
    { name: "pot_plant", x: 18, y: 8 },
    { name: "pot_plant", x: 20, y: 8 },
    { name: "pot_plant", x: 9, y: 24 },
    { name: "pot_plant", x: 29, y: 24 },
    // chest
    { name: "chest", x: 12, y: 5 },
    { name: "chest", x: 28, y: 5 },
    { name: "chest", x: 20, y: 12 },
    // base
    { name: "woodFenceNoEdge", x: 18, y: 24 },
    { name: "woodFenceNoEdge", x: 18, y: 23 },
    { name: "woodFenceNoEdge", x: 18, y: 22 },
    { name: "woodFenceNoEdge", x: 19, y: 22 },
    { name: "woodFenceNoEdge", x: 21, y: 24 },
    { name: "woodFenceNoEdge", x: 21, y: 23 },
    { name: "woodFenceNoEdge", x: 21, y: 22 },
    { name: "woodFenceNoEdge", x: 20, y: 22 },
    // water
    { name: "water", x: 24, y: 6 },
    { name: "water", x: 16, y: 6 },
    { name: "water", x: 10, y: 15 },
    { name: "water", x: 30, y: 15 },
  ] as Obstacle[],

}
